import { NextResponse } from 'next/server';
import { prompt, getConfiguredAIProviders, type AITask } from '@/lib/aiWaterfall';
import { deleteDoc, getDoc, isFirebaseConfigured, listDocs, setDoc } from '@/lib/firebase';
import { readCookie, SESSION_COOKIE, verifySession } from '@/lib/session';

const COLLECTION = 'ai_profiles';
const TASKS: AITask[] = ['scout','factCheck','analyst','writer','editor','guardian','general'];
type Profile = { id:string; name:string; description?:string; mode:'best-quality'|'free-only'|'low-cost'|'fast'|'custom'; defaultProvider?:string; taskProviders:Partial<Record<AITask,string>>; temperature:number; maxTokens:number; createdAt:string; updatedAt:string };
async function isAdmin(req:Request){const token=readCookie(req.headers.get('cookie'),SESSION_COOKIE);return !!(token&&await verifySession(token));}
function safeProfile(p:Partial<Profile>,id:string):Profile{return {id,name:typeof p.name==='string'?p.name.slice(0,80):'Custom Profile',description:typeof p.description==='string'?p.description.slice(0,300):'',mode:['best-quality','free-only','low-cost','fast','custom'].includes(p.mode as string)?p.mode as Profile['mode']:'custom',defaultProvider:typeof p.defaultProvider==='string'?p.defaultProvider.slice(0,100):undefined,taskProviders:Object.fromEntries(Object.entries(p.taskProviders||{}).filter(([k,v])=>TASKS.includes(k as AITask)&&typeof v==='string').map(([k,v])=>[k,String(v).slice(0,100)])),temperature:Math.min(1.5,Math.max(0,Number.isFinite(Number(p.temperature))?Number(p.temperature):.4)),maxTokens:Math.min(16000,Math.max(128,Number.isFinite(Number(p.maxTokens))?Math.round(Number(p.maxTokens)):4096)),createdAt:p.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};}
const fallbackProfiles:Profile[]=[{id:'best-quality',name:'Best Quality',description:'Strongest available model for each role.',mode:'best-quality',taskProviders:{},temperature:.35,maxTokens:6000,createdAt:'',updatedAt:''},{id:'free-only',name:'Free Only',description:'Never select paid providers.',mode:'free-only',taskProviders:{},temperature:.4,maxTokens:5000,createdAt:'',updatedAt:''},{id:'fast',name:'Fast',description:'Prefer responsive providers.',mode:'fast',taskProviders:{},temperature:.45,maxTokens:3500,createdAt:'',updatedAt:''}];
export async function GET(req:Request){if(!await isAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});let profiles=fallbackProfiles;if(isFirebaseConfigured()){try{profiles=(await listDocs<Profile>(COLLECTION,{pageSize:50})).data;}catch{}}return NextResponse.json({profiles,providers:getConfiguredAIProviders(),tasks:TASKS});}
export async function POST(req:Request){if(!await isAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});let body:any;try{body=await req.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}
 if(body.action==='test'){const text=typeof body.prompt==='string'?body.prompt.slice(0,6000):'';if(!text)return NextResponse.json({error:'Prompt is required'},{status:400});try{const r=await prompt('You are Qawla AI Studio. Produce precise, useful editorial output. Never invent facts.',text,{task:(body.task||'general') as AITask,preferredProvider:body.defaultProvider,allowPaid:body.mode!=='free-only',profileMode:body.mode,temperature:body.temperature,maxTokens:body.maxTokens});return NextResponse.json({result:r.content,provider:r.provider,model:r.model,tokensIn:r.tokensIn,tokensOut:r.tokensOut,durationMs:r.durationMs,attempts:r.attempts});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'AI test failed'},{status:502});}}
 if(!body.name)return NextResponse.json({error:'Profile name is required'},{status:400});if(!isFirebaseConfigured())return NextResponse.json({error:'Firebase is required to persist AI profiles.'},{status:503});const now=new Date().toISOString(),id=crypto.randomUUID(),profile=safeProfile({...body,createdAt:now},id);await setDoc(COLLECTION,id,profile);return NextResponse.json({profile},{status:201});}
export async function PATCH(req:Request){if(!await isAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});if(!isFirebaseConfigured())return NextResponse.json({error:'Firebase is required to persist AI profiles.'},{status:503});let body:any;try{body=await req.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}if(!body.id)return NextResponse.json({error:'Profile id is required'},{status:400});const current=await getDoc<Profile>(COLLECTION,body.id);if(!current)return NextResponse.json({error:'Profile not found'},{status:404});const profile=safeProfile({...current,...body},body.id);await setDoc(COLLECTION,body.id,profile);return NextResponse.json({profile});}
export async function DELETE(req:Request){if(!await isAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});if(!isFirebaseConfigured())return NextResponse.json({error:'Firebase is required to persist AI profiles.'},{status:503});const id=new URL(req.url).searchParams.get('id');if(!id||!/^[A-Za-z0-9_-]{1,120}$/.test(id))return NextResponse.json({error:'Valid profile id is required'},{status:400});await deleteDoc(COLLECTION,id);return NextResponse.json({ok:true});}
